### ISSUE TITLE
Add engine for Twig

### ISSUE THREAD

**Issue by MPParsley** [qltysh/codeclimate#1003]
Could you add an engine for Twig, Eg. https://github.com/friendsoftwig/twigcs

**Comment by MPParsley** [comment]
oi Filipe, tudo bem? :-) 🇧🇷 

Are you going to work on a twig engine for code climate? Sería tri legal 👍

**Comment by filipesperandio** [comment]
Opa!
Não temos planos infelizmente, mas contribuições são sempre bem vindas.

Se tiver interesse em criar o plugin, pode seguir as documentações aqui:
https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md
https://github.com/codeclimate-community/submissions

ou usar um desse repositorios como exemplo:
https://github.com/codeclimate-community/submissions/blob/master/manifest.yml

:D

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
