### ISSUE TITLE
Updating to Rails 5.2.5 generates bundler-audit warnings

### ISSUE THREAD

**Issue by fabiolnm** [qltysh/codeclimate#1011]
<img width="500" alt="Screen Shot 2021-03-27 at 07 50 53" src="https://user-images.githubusercontent.com/508671/112718397-6e9ca200-8ed1-11eb-8d9a-a84ce5c4b3c5.png">

### Temporary workaround

Modify the `.codeclimate.yml` file to mark the engine as disabled.
```
engines:
  bundler-audit:
    enabled: false
```

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
