### ISSUE TITLE
Suggestions regarding docker image

### ISSUE THREAD

**Issue by DannyBen** [qltysh/codeclimate#1016]
I followed the clear instructions of manually using the docker image, and after running the container, it took a long time to run. After running it in debug mode, I realized that it pulls additional >5GB containers.

To me (and I am sure to some others), it looked like it just "hangs" since the pulling of the additional images takes way too long, and I know my project usually runs in a few seconds on the cloud service.

So, based on this experience, I would like to suggest to update the docker pull instructions to instruct users to pre-download the additional images and not only the base image:

```
$ docker pull codeclimate/codeclimate
$ docker pull codeclimate/codeclimate-structure
$ docker pull codeclimate/codeclimate-duplication
```

In addition, I can say that these docker images are the largest I have ever seen, by a huge factor. I am guessing the reason is that they contain all the tools for all the languages. It would be much nicer to have smaller (<1GB) images, on a per-language basis, and even better - to have these images work without the need to use docker-in-docker.

I know the chances of this happening are slim to none, but I thought I should mention it, in case someone else in the code climate team is thinking along these lines.

**Comment by thelooter** [comment]
Any update on this?

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
