### ISSUE TITLE
problem with CODECLIMATE_PREFIX with CODECLIMATE_DEV=1

### ISSUE THREAD

**Issue by iakshat** [qltysh/codeclimate#1027]
Hi there!

I'm trying to use my own registry with the CLI. I think there are problems when we use CODECLIMATE_PREFIX with our custom engines. Maybe [here](https://github.com/codeclimate/codeclimate/blob/9dd3ec88b4d655c2b42df7290b09a1ee4f14ae2a/lib/cc/engine_registry.rb#L31) we have not included prefix in the engine's command like in line 37 in the same file for default engine. Can you help me out with some workaround

can you please help me fix this asap as there is an urgent need for completion of my project

Edit: updated the link

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
