### ISSUE TITLE
Auto ignore files declared on `.gitignore`

### ISSUE THREAD

**Issue by f-moya** [qltysh/codeclimate#1028]
I faced an `invalid json` error while running the `eslint` plugin over a project. The root of the problem seems to be a memory allocation error. The CLI was analyzing files that I have under `public/pacs` where a lot of `application-<hash>.js` files live, this folder is ignored on `.gitignore` that's why I didn't face this issue when using the plugin on [codeclimate.com](https:://codeclimate.com). All this considered, it might be a good idea to auto ignore files declared on `.gitignore`

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
