### ISSUE TITLE
Support for mounting /code directory read-write when analyzing?

### ISSUE THREAD

**Issue by lizalc** [qltysh/codeclimate#1029]
As shown in [`lib/cc/analyzer/engine.rb` line 84](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/engine.rb#L84) the code volume (mapped to `/code` in the analyzer) is mounted read-only. This prevents the usage of analyzers which need to generate extra files when performing analysis. For me personally, this prevents the use of the [MISRA add-on ](http://cppcheck.sourceforge.net/misra.php) when analyzing C code with [`cppcheck`](http://cppcheck.sourceforge.net/) via a slightly modified version of the [`codeclimate-cppcheck` analyzer](https://github.com/antiagainst/codeclimate-cppcheck). The MISRA add-on works by having `cppcheck` generate additional `.dump` files of the code and then using the `.dump` files to perform the MISRA analysis.

Currently I'm working around this by generating the `.dump` files in an action that runs before my Code Climate `cppcheck` action that way the `.dump` files are present in the `/code` directory before analysis is performed. This isn't completely ideal though since have to manage two separate `cppcheck` actions.

Would it be feasible to allow the `/code` directory to be mounted read-write when running certain analyzers? Maybe via a user config option or some other method?

Some other discussion is here in the `codeclimate-cppcheck` repo: https://github.com/antiagainst/codeclimate-cppcheck/issues/41

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
