### ISSUE TITLE
[Question] Atom plugin for Windows

### ISSUE THREAD

**Issue by sabatale** [qltysh/codeclimate#1042]
**Product**
linter-codeclimate (for Atom)

**Question**
Is there a workaround to make the plugin compatible with Docker on Windows since the CLI cannot be installed directly? The post [https://github.com/codeclimate/codeclimate/issues/864](https://github.com/codeclimate/codeclimate/issues/864) helps a little when it comes to Windows, but not within the context of Atom. Thanks!

E.g., `docker run -it --rm --env CODECLIMATE_CODE="/C/Projects/Example/App" -v C:\Projects\Example\App:/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate analyze`

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
