### ISSUE TITLE
Codeclimate is throwing security issue for AWS Lambda ephemeral storage

### ISSUE THREAD

**Issue by vineetsharma883** [qltysh/codeclimate#1062]
I am using codeclimate for code quality checks and recently started facing issue `Probable insecure usage of temp file/directory` import for AWS Lambda ephemeral storage. The code has usage for `/tmp/` directory in the way - `os.makedirs(f"/tmp/my-repo/{file_path}", exist_ok=True)`. Is it possible to ignore lambda ephemeral storage for `/tmp/` storage checks.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
