### ISSUE TITLE
Support for Golang seems to be unmaintained

### ISSUE THREAD

**Issue by timo-klarshift** [qltysh/codeclimate#1063]
Hello,

I wonder if codeclimate has enough maintainers, because it seems like nobody is looking into engine related issues:
- https://github.com/codeclimate/codeclimate-golint/issues/18
- https://github.com/codeclimate/cc-engine-go/issues/4
- https://github.com/codeclimate/codeclimate-golint/issues/28

I was quite happy with codeclimate at first, but it seems you dont care about golang as the latest version there is `1.3.0`

Could you please elaborate if you plan to support Golang also in the future or if I should look for an alternative.

Also I dont think its worth it providing a PR as they seem not to be handled at all: https://github.com/codeclimate/codeclimate-golint/pull/21

**Comment by stefan-ctrl** [comment]
Once Go support will be revisited, may I suggest using golangci-lint as the main linter: https://github.com/golangci/golangci-lint

**Comment by shenma6** [comment]
we need golang support

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
