### ISSUE TITLE
add engine for salt-lint

### ISSUE THREAD

**Issue by ITJamie** [qltysh/codeclimate#1065]
Feature request / engine request

linter: salt-lint
docs: https://salt-lint.readthedocs.io/en/latest/
https://github.com/warpnet/salt-lint

salt-lint is used for linting sls files for saltstack.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
