### ISSUE TITLE
Feature request: Plugin to detect secret sprawl

### ISSUE THREAD

**Issue by MPParsley** [qltysh/codeclimate#1080]
Is there a CodeClimate plugin that is able to detect secrets in the source code?

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
