### ISSUE TITLE
CppCheck report a huge input error when scan big c++ repo

### ISSUE THREAD

**Issue by zjkyz8** [qltysh/codeclimate#1089]
Hi guys,

When I use cppcheck to scan a big c++ repo, an error of "huge input" was thrown. This is caused by [codeclimate-cppcheck](https://github.com/antiagainst/codeclimate-cppcheck). I already made a [PR](https://github.com/antiagainst/codeclimate-cppcheck/pull/48) to fix it. So would please update the cppcheck engine image?

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
