### ISSUE TITLE
Publish pipeline failed for version 0.93

### ISSUE THREAD

**Issue by motizuki** [qltysh/codeclimate#1104]
Hi there!
We've been getting this warning in our pipeline:
```
WARNING: A new version (v0.93.0) is available. Upgrade instructions are available at: https://github.com/
codeclimate/codeclimate#packages
```
However, the image is not available on Docker Hub, and it looks like the `publish` pipeline for the version 0.93 is failing.

Can someone look into this?

Publish pipeline:
https://app.circleci.com/pipelines/github/codeclimate/codeclimate/418/workflows/a36aa63b-6ac4-4a3d-a02e-478ed76cb95c/jobs/3045

Thanks :)

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
