### ISSUE TITLE
CONTAINER_TIMEOUT_SECONDS not honored?

### ISSUE THREAD

**Issue by ahazem** [qltysh/codeclimate#1116]
Hi 👋🏼

I cannot seem to get `CONTAINER_TIMEOUT_SECONDS` to be honored by the `codeclimate` docker image.

Below is the command I ran, locally on my machine:

```
docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --env CODECLIMATE_DEBUG=1 \
  --env CONTAINER_TIMEOUT_SECONDS=5 \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze
```

On the code from the following repository, which is a fresh installation of a [remix](https://remix.run/) app:

https://github.com/ahazem/fresh-node-remix-app

And here are the timings from the output:

```
I, [2023-05-24T20:35:40.961899 #1]  INFO -- : starting engine structure
I, [2023-05-24T20:35:55.108455 #1]  INFO -- : finished engine structure
I, [2023-05-24T20:35:55.108664 #1]  INFO -- : starting engine duplication
I, [2023-05-24T20:36:00.246367 #1]  INFO -- : finished engine duplication
```

I expected the container running structure engine to be killed after 5 seconds, but it kept running for approximately 15 seconds!
 
I ran this on macos ventura (13.4) but running this on CI using unix-based OSes seem to have similar results.

Output of `docker version` and other commands:

```
# uname -a
Darwin MBP 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

# docker version
Client:
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:14:58 2023
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Tue May  9 02:02:55 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:

# env | grep "^DOCKER_"

```

Is there anything I'm doing wrong or missing here? 🤔

**Comment by ahazem** [comment]
@RubyBrewsday sorry to ping you directly here, but is there any feedback or thoughts you might have on the above? 🙏🏼

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
