### ISSUE TITLE
ImagePullFailure error 

### ISSUE THREAD

**Issue by 500poundbear** [qltysh/codeclimate#1117]
Hi,

I'm encountering a error about the pulling of the `codeclimate/codeclimate-structure` image. Since I am hosting it on a local image repository, this is the image that I pull is from `[LOCAL-IMAGE-REPO]:6555/codeclimate/codeclimate-structure`.

This is the error from running `/run.sh $CI_PROJECT_DIR`

```
error: (CC::CLI::Engines::Install::ImagePullFailure) unable to pull image [LOCAL-IMAGE-REPO]:6555/codeclimate/codeclimate-structure
D, [2023-06-08T08:27:23.265347 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/cli/engines/install.rb:27:in `pull_engine'
	/usr/src/app/lib/cc/cli/engines/install.rb:21:in `each'
	/usr/src/app/lib/cc/cli/engines/install.rb:21:in `pull_docker_images'
	/usr/src/app/lib/cc/cli/engines/install.rb:11:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
Could not install code climate engines for the repository at /builds/
```

For safe measure, I have added additional steps to test the pulling of the image before running `/run.sh $CI_PROJECT_DIR`.

```
docker pull [LOCAL-IMAGE-REPO]::6555/codeclimate/codeclimate-structure
....
```

The docker image seems to be saved correctly too.
```
$ docker images
REPOSITORY                                                           TAG       IMAGE ID       CREATED       SIZE
[LOCAL-IMAGE-REPO]:6555/codeclimate/codeclimate-structure   latest    90c83a1306e8   2 years ago   5.63GB
```

Please let me know if there are any remediation steps for the above. Thanks!

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
