### ISSUE TITLE
Please release sonar-java-7-2 

### ISSUE THREAD

**Issue by toninin** [qltysh/codeclimate#1120]
Hey there!

We are using codeclimate in our pipeline as provieded by GitLab.
https://docs.gitlab.com/ee/ci/testing/code_quality.html#using-analysis-plugins

As you can see here, GitLab's template uses the newest version of codeclimate, which is 0.96.0
https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Code-Quality.gitlab-ci.yml?ref_type=heads.

The `sonar-java-7-2` channel is not available in the newest version, even though it was already configured in https://github.com/codeclimate/codeclimate/pull/1119 .

Can you add a new release to make sonar-java-7-2 available please? I could then overwrite GitLabs codeclimate version and use the new release right away.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
