### ISSUE TITLE
HTML output add severity field

### ISSUE THREAD

**Issue by leffss** [qltysh/codeclimate#1121]
Hi Thank you for your project！

In json output every issue has severity field，but if output is html，there is no severity field for filtering.

If possible, please add a severity field in the HTML.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
