### ISSUE TITLE
Add libyear support

### ISSUE THREAD

**Issue by amkisko** [qltysh/codeclimate#1124]
Hey!

There is a tool that falls under codeclimate domain fully called libyear, the `libyear` metric can be introduced per language and will be quite useful for keeping the dependencies fresh by following this metric.

References:
- https://libyear.com
> A simple measure of software dependency freshness. It is a single number telling you how up-to-date your dependencies are.
- https://github.com/search?q=libyear&type=repositories

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
