### ISSUE TITLE
Reek plugin is executed under ruby-2.6 with parser-3.2.1.0

### ISSUE THREAD

**Issue by bannable** [qltysh/codeclimate#1127]
Example build: https://codeclimate.com/github/bannable/paseto/builds/561
Project: https://github.com/bannable/paseto

The reek plugin is executed under ruby-2.6 with parser-3.2.1.0, making it fully incompatible with any ruby syntax changes since 3.0.

Ruby-2.6 has been End Of Support since 31 Mar 2022. I originally reported this to CC in support ticket 49634.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
