### ISSUE TITLE
Support for C# Asp.net MVC project on  .net framework 4.8

### ISSUE THREAD

**Issue by chulliyilmahesh** [qltysh/codeclimate#1128]
Hi there!

I went through all your documentation and couldn't find anything related to my question. We have codeclimate accessible with our GitLab license. So was trying to see it we can implement code quality scan for our asp.net mvc project in .net framework 4.8.  This project work on windows machines unlike dotnet 5+ projects which can be built and run on linux machines. 

Thanks,
Mahesh

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
