### ISSUE TITLE
How to use tflint with a subdirectory?

### ISSUE THREAD

**Issue by jrobison-sb** [qltysh/codeclimate#1130]
- Include the exact command you're running and its complete output

```
$ codeclimate analyze
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Starting analysis
Running structure: Done!
Running duplication: Done!
Running tflint: Done!
error: (CC::CLI::Analyze::EngineFailure) engine tflint failed with status 1 and stderr 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2024/08/08 17:36:29 [main.go/main] Extracting configuration...
2024/08/08 17:36:29 [main.go/getConfigurationArgs] Reading config.json file...
2024/08/08 17:36:29 [main.go/getConfigurationArgs] Unmarshaled CodeClimate configuration: &{[] [LIST OF FILES IN MY REPOSITORY REDACTED]}
2024/08/08 17:36:29 [main.go/getConfigurationArgs] Unmarshaled TFLint configuration: &{{terraform/modules/aws/application/.tflint.hcl [] [] [] [] []  [] false}}
2024/08/08 17:36:29 [tflint/configuration.go/ToCLIArguments] Converting configuration file to CLI args...
2024/08/08 17:36:29 [tflint/configuration.go/ToCLIArguments] Setting --config=terraform/modules/aws/application/.tflint.hcl
2024/08/08 17:36:29 [tflint/configuration.go/ToCLIArguments] Finished extracting arguments from TFLint configuration
2024/08/08 17:36:29 [main.go/main] Extracted TFLint configuration: [tflint --force --format=json --config=terraform/modules/aws/application/.tflint.hcl]
2024/08/08 17:36:29 [main.go/main] Generated glob pattern from ExcludePatterns: {}
2024/08/08 17:36:29 [main.go/main] File is NOT matching exclude_patterns, adding it to args: terraform/state.tf
2024/08/08 17:36:29 [main.go/main] Running TFLint with args: [tflint --force --format=json --config=terraform/modules/aws/application/.tflint.hcl terraform/state.tf]
17:36:29 main.go:88: [main.go/main] Completed TFLint run with output: {"issues":[],"errors":[{"message":"Failed to initialize plugins; Plugin `terraform` not found in /home/app/.tflint.d/plugins","severity":"error"}]}
17:36:29 main.go:91: [main.go/main] Converting TFLint output to CodeClimate format...
17:36:29 formatter.go:143: no match found for given string
  ```

- Indicate what you expected to happen and what happened instead

My repository structure looks like this:
```
root@531a10c4f792:/my_repo# tree
.
|-- ansible
|-- project1
|-- project2
|-- project3
`-- terraform
    |-- modules
    |   `-- aws
    |       |-- application
    |       |   |-- ec2.tf
    |       |   |-- ecs.tf
    |       |   `-- vpc.tf
    |       |-- bar
    |       |-- baz
    |       `-- foo
    `-- state.tf
```

The files I'm interested in running through static analysis are the `terraform/modules/aws/application/*.tf` files. I don't currently care about scanning any other files/directories in this repository.

When I run `tflint` outside of the context of CodeClimate, I can run it like this and it works great:

```
$ tflint --chdir=terraform/modules/aws/application/
81 issue(s) found:

...
```

I can't find any way to specify `-chdir=terraform/modules/aws/application/` as part of the `.codeclimate.yml` file. Anything resembling `--chdir` isn't mentioned in [the CodeClimate docs](https://docs.codeclimate.com/docs/tflint). And when I check the version of `tflint` inside the `codeclimate/codeclimate-tflint` image, I see that the version is `0.39.3`, which is prior to when `--chdir` even existed. (`--chdir` [was introduced in tflint 0.44.0](https://github.com/terraform-linters/tflint/blob/master/CHANGELOG.md#0440-2022-12-26).)

```
$ docker image inspect codeclimate/codeclimate-tflint | jq -r '.[0].RepoDigests[0]'
codeclimate/codeclimate-tflint@sha256:25e7daffdffb40ae8de2ca2b7ab1de0c322a07232b2f42563902c325eb46a6f0

$ docker run -it --rm --platform linux/amd64 codeclimate/codeclimate-tflint tflint --version
TFLint version 0.39.3
```

I suspect that `tflint` needs to be upgraded in the Docker image, and then Codeclimate will need to support new tflint options in `.codeclimate.yml`.

Additionally, as seen in the output above (`Failed to initialize plugins; Plugin 'terraform' not found in /home/app/.tflint.d/plugins`), how can Codeclimate be instructed to install tflint plugins inside the Docker container? Usually this would be done by running `tflint --init`, but I don't see any ability to pass that through Codeclimate.

I suspect that the plugin installation error is probably also related to the oldness of `tflint` in the Docker image, because tflint 0.40.0 "[contains major changes to the plugin system](https://github.com/terraform-linters/tflint/blob/master/CHANGELOG.md#0400-2022-09-08)", which the Codeclimate Docker image wouldn't have as it uses 0.39.3.

Additional details if needed:

  ```
$ codeclimate --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
0.96.0
```

```
$ cat .codeclimate.yml 
# https://docs.codeclimate.com/docs/advanced-configuration

version: "2"
plugins:
  tflint:
    enabled: true
    config:
      config: terraform/modules/aws/application/.tflint.hcl

$ cat terraform/modules/aws/application/.tflint.hcl 
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}

plugin "aws" {
    enabled = true
    version = "0.32.0" # This is the version of the ruleset, not the terraform provider. It corresponds with a git tag in the ruleset repository.
    source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

- Include your operating system, how you run Docker (e.g. Docker Machine) and
  the version of Docker you're using.

  Include the output of the following commands:

```
$ uname -a
Darwin SB00994 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 arm64

$ docker version
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ env | grep -c "^DOCKER_"
0
```

- If your project is open source, please provide a URL to the source

It's not open source.

- If your project is closed source, but you'd be willing to share a copy with us
  (for example, by emailing an archive), please say so

We probably couldn't share the whole entire repo, but I wouldn't be opposed to making a minimum viable reproduce case if needed.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
