### ISSUE TITLE
Reek engine outdated, how to contribute?

### ISSUE THREAD

**Issue by josemigallas** [qltysh/codeclimate#1132]
According to https://docs.codeclimate.com/docs/reek, it uses the stable version of reek but I think this information is outdated. The latest stable version is [6.3.0](https://github.com/troessner/reek/releases/tag/v6.3.0) according to reek.

What would be the way to update this as a contribution to codeclimate? Is there a repo for reek like there is for [rubocop](https://github.com/codeclimate/codeclimate-rubocop)?

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
