### ISSUE TITLE
codeclimate-structure fails parsing Ruby 3 syntax

### ISSUE THREAD

**Issue by tatethurston** [qltysh/codeclimate#1133]
Similar to https://github.com/codeclimate/codeclimate-duplication/issues/375 codeclimate/codeclimate-structure is not working with Ruby 3 syntax, eg https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted released Dec 2021.

I can't find the repository for codeclimate-structure under the codeclimate or codeclimate-community org, please redirect me if there is a repository for codeclimate-structure. 

Updating ruby_parser will resolve the issue: https://github.com/codeclimate-community/codeclimate-flog/pull/16/files.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
