### ISSUE TITLE
Show progress during Makefile install process

### ISSUE THREAD

**Issue by noahd1** [qltysh/codeclimate#150]
I installed the CLI via brew and it took 3.5 minutes. I looked at the process list and likely most of that time was taken up by updating local docker images. This seems fine, but more progress output would have been helpful, as it looked like the install had hung.

```
[2.2.2][21:16][~]$ brew install codeclimate
==> Installing codeclimate from codeclimate/homebrew-formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.8.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/codeclimate-0.8.1.tar.gz
==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PREFIX=/usr/local/Cellar/codeclimate/0.8.1 ma
🍺  /usr/local/Cellar/codeclimate/0.8.1: 4 files, 16K, built in 3.6 minutes
```

**Comment by noahd1** [comment]
Alternatively, don't run the docker pull during install, but print post-install instructions to do so.

**Comment by pbrisbin** [comment]
I'm in favor of being more explicit and telling the user a command to run to update engines images. However, others may want to err on the side of convenience, which I'm fine with, and agree we should be showing some output (if possible) so it doesn't appear frozen.

**Comment by taiidani** [comment]
This issue seems stale, but I want to add my support for it. My `make install` took over 7 minutes. I ended up executing `watch 'sh -c "docker image ls | grep code"'` just so I had some proof that it wasn't frozen.

```
$ brew reinstall codeclimate
==> Reinstalling codeclimate/formulae/codeclimate
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.72.0.tar.gz
==> make install
🍺  /usr/local/Cellar/codeclimate/0.72.0: 5 files, 43.6KB, built in 7 minutes 14 seconds
```

**Comment by taiidani** [comment]
That definitely shows the output! Now if only that were the default :)

At the least that gives me an easy response for developers wanting to know what's going on under the hood during their installs.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
