### ISSUE TITLE
Support for JSONLint

### ISSUE THREAD

**Issue by devth** [qltysh/codeclimate#329]
http://jsonlint.com/

**Comment by dblandin** [comment]
Hi @devth,

Not sure when we'll be able to get to this ourselves but if you're interested in creating a JSONLint engine for the Code Climate Platform, you can find our open source spec [here](https://github.com/codeclimate/spec).

**Comment by devth** [comment]
Thanks @dblandin. Not sure when I'll be able to get to it either :)

**Comment by kalmbach** [comment]
@devth @dblandin I want to work on this, will give it a try.

**Comment by dblandin** [comment]
@kalmbach Awesome! Let me know if I can be of any help! You can reach me via email at devon@codeclimate.com.

**Comment by dblandin** [comment]
Hey @devth @kalmbach,

Just wanted to let you two know that we've created a new codeclimate-community slack organization. The discussion so far has been focused around engine ideas and development. If you're already part of the Developer Program you should have received an invite already. If not, you can [sign up here](https://codeclimate.com/dev_form) and join the discussion!

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
