### ISSUE TITLE
Is a slim-lint engine on the roadmap?

### ISSUE THREAD

**Issue by monfresh** [qltysh/codeclimate#418]
It would be great to add support for [slim-lint](https://github.com/sds/slim-lint). Any idea if/when that would be possible?

**Comment by dblandin** [comment]
Hey @monfresh! Agreed! That looks like a useful tool and would certainly make a great engine addition to the Code Climate Platform.

If you're interested in creating the engine or want to gauge interest from other developers, I encourage you to join our [Developer Program](https://codeclimate.com/dev_form) and pitch it in our new codeclimate-community slack organization.

While this repo has been a common landing pad for engine ideas, the new slack organization should serve as a more productive channel for engine-related discussion.

Thanks!

**Comment by monfresh** [comment]
Great! Will do!

**Comment by parndt** [comment]
Did anything result from the chat? 😄

**Comment by dblandin** [comment]
> Did anything result from the chat?

@parndt Not that I'm aware of but there are a couple in-progress haml-lint engines that should be similar to a slim-lint implementation since haml-lint also sits on top of rubocop:

https://github.com/michaelherold/codeclimate-haml_lint by @michaelherold (under active development)
https://github.com/rafdizzle86/codeclimate-haml-lint by @rafdizzle86 (inactive)

**Comment by michaelherold** [comment]
I don't use Slim myself, but I'd be up for making an engine for slim_lint through sponsorship if it's important to you.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
