### ISSUE TITLE
Engine Request: Puppet engine

### ISSUE THREAD

**Issue by sysadmiral** [qltysh/codeclimate#437]
I was wondering if a puppet engine was planned? Given that a chef engine exists...

There is puppet-lint (rubygem) available and puppet validate (although I don't think the output is usable/useful).

**Comment by pbrisbin** [comment]
Hi @sysadmiral, we don't have any specific plans for a puppet engine at the moment but that doesn't mean it won't happen. Certainly if you (or anyone) would like to work on wrapping puppet-lint up as an Engine, we'd love to have it.

We actually have a codeclimate-community slack organization where folks hang out to discuss engine ideas and development. If you're interested (you don't have to be authoring an engine to participate in the discussion), you can [join our Developer Program](https://codeclimate.com/dev_form) to get an invite.

**Comment by bittner** [comment]
There is a `pdk validate` command now for linting file formats present in Puppet modules. See [Validating and testing modules](https://puppet.com/docs/pdk/1.x/pdk_testing.html#ariaid-title2) using the [Puppet Development Kit](https://puppet.com/docs/pdk/latest/pdk.html).

**Comment by maxjacobson** [comment]
Neat. If you (or someone else reading this) are interested in spearheading the effort to add a Puppet engine, I'd recommend:

- [reading the overview of the engine spec](https://github.com/codeclimate/spec/)
- [joining the community slack](https://codeclimate.com/dev_form) where you can ask for help as you work on it, and ping us when you're ready to add the engine to the CLI and codecliimate.com

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
