### ISSUE TITLE
Disable animations when terminal incapable of displaying

### ISSUE THREAD

**Issue by zenspider** [qltysh/codeclimate#540]
Checking `.tty?` isn't enough to determine whether you should do fancier terminal output and can result in output looking like:

```
[1GRunning flog: |[1GRunning flog: /[1GRunning flog: -[1GRunning flog: \[1GRunning flog: |[1G
Running flog: /[1GRunning flog: -[1GRunning flog: \[1GRunning flog: |[1GRunning flog: /[1G
Running flog: -[1GRunning flog: \[1GRunning flog: |[1GRunning flog: /[1GRunning flog: -[1G
Running flog: \[1GRunning flog: Done!
```

In minitest, I use:

```ruby
klass = ENV["TERM"] =~ /^xterm|-256color$/ ? PrideLOL : PrideIO
```

**Comment by pbrisbin** [comment]
I'm not sure the most robust way to do this, but just wanted to note that that regex is too restrictive IMO. Lots of terminals which are neither xterm nor 256color-capable should still be able to show our spinner and limited coloring. The most notable would be `screen`.

It might be more valuable to avoid certain "known-dumb" `TERM`s (like `linux`). @zenspider can you tell me what your `TERM` was when you uncovered this?

I think @wfleming mentioned matching tools like `ls` and `grep` which have an `auto|always|off` argument to their `--color` options. I'm :+1: on that, in addition to matching their implementation of "auto".

**Comment by zenspider** [comment]
In emacs' shell, `TERM=dumb`.

I have yet to have anyone complain about my choice for minitest's pride being too restrictive. In general, I much prefer whitelisting to blacklisting so I know what I am getting, but I'm fine with whatever as long as I don't have to remember a flag every time.

**Comment by zenspider** [comment]
Oh, and the "right" way of doing this would be to test capability via termcap. In the case of screen:

```
screen|VT 100/ANSI X3.64 virtual terminal:\
[...lots of crap]...:tc=ecma+color:
```

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
