### ISSUE TITLE
pep8 1.6.2 update to pycodestyle 2.2.0

### ISSUE THREAD

**Issue by IceflowRE** [qltysh/codeclimate#549]
Hi there!

Sorry you're having trouble with our CLI, and thanks for taking the time to
report the issue to us.

There are a few reasons _not_ to open an issue here. Please consider the
following:

- Is this an issue with codeclimate.com?
**Yes, sure.**

  If you're having trouble with our hosted analysis available on
  codeclimate.com, please use our [Help & Support](https://codeclimate.com/help)
  form.

- Is this an issue with a specific engine?
**Yes.**

  Please report issues about a specific engine to that engine's repository. It
  can usually be found at `codeclimate/codeclimate-<engine>`. If you can't find
  the engine's repository (or Issues aren't enabled there), please do report
  your issue here.
**No. Support mentioned to ping here. And the pep8 repo has no issue section.**

At least:

Code Climate uses pep8 1.6.2, which is outdated. The newest version is pycodestyle 2.2.0. (https://github.com/PyCQA/pycodestyle)
pep8 has been renamed too. An update would be very pleasant.

**Comment by tedmiston** [comment]
I'd really like to have this updated to the latest as well.  Is there anything we can do to help from the dev side?

**Comment by anil-kamath** [comment]
Hi,
Is there any progress on this issue?
Being stuck to `pep8 1.6.2` instead of the latest `pycodestyle 2.7.0` is causing CC to show warnings for newly introduced features such as the walrus `:=` operator https://www.python.org/dev/peps/pep-0572/

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
