### ISSUE TITLE
Stderr isn't dumped if any JSON issue fails to parse/typecheck

### ISSUE THREAD

**Issue by zenspider** [qltysh/codeclimate#562]
Basically a transcript from slack, me unless specified:

for some reason my stderr output isn’t being displayed when I have `CODECLIMATE_DEBUG` set… is there something I’m forgetting? I am running with `—dev`

it USED to print out.... I swear.

ooooh… ok. I think I get it. If I print an incorrect issue, `{}` in this case, then CC blows up and I don’t see any of stderr. If I bypass that error, then I do see it.

I’m doing the equiv of `CODECLIMATE_DEBUG=1 codeclimate analyze --dev | cat`

Pat Brisbin: cool, so it seems an ordering problem with the printing of the stderr and the validation-triggered exception?

yeah, I think so. might be designed that way… but it’d help a dev if stderr was dumped out at the point of aborting

Pat Brisbin: probably not intentional, but it's tough to think of it that way because it's the engine's stderr not `codeclimate`'s

```
          unless output.valid?
            stdout_io.failed("#{qualified_name} produced invalid output: #{output.error[:message]}")
            container.stop
          end
```

Pat Brisbin: so when an engine completes (success or fail) you dump its stderr. i thought we tried to dump it as it ran, but there might be buffering issues

vs 2 paragraphs below:

```
        container.run(container_options).tap do |result|
          CLI.debug("#{qualified_name} engine stderr: #{result.stderr}")
        end
```

so, not sure HOW you’d capture the stderr at the point above

Pat Brisbin: yeah. ideally that'd be re-oriented such that it's line-bufferred directly out instead of pushed into `result.stderr` for later (edited)

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
