### ISSUE TITLE
Feature request: Engine for clang-tidy

### ISSUE THREAD

**Issue by nocnokneo** [qltysh/codeclimate#707]
Adding an engine for [clang-tidy](http://clang.llvm.org/extra/clang-tidy/) would be great for C++ projects!

**Comment by dblandin** [comment]
Hey @nocnokneo,

We don't have any plans for a clang-tidy engine right now but if you (or anyone) would like to work on wrapping clang-tidy up as an engine, we'd love to have it. You can find our open source spec [here](https://github.com/codeclimate/spec).

We have a Slack organization setup to facilitate communication on the Platform and engine development. You can receive an invite by joining our developer program: https://codeclimate.com/dev_form

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
