### ISSUE TITLE
Feature request: engine for elixir dialyzer

### ISSUE THREAD

**Issue by kelvinst** [qltysh/codeclimate#711]
Elixir as it is don't have static type checking, but there is an erlang tool called `dialyzer` which makes it easy to configure typespecs and check them.

There is the project [dialyxir](https://github.com/jeremyjh/dialyxir) which can be used to run dialyzer on elixir projects a little bit easier.

**Comment by ale7714** [comment]
Hi @kelvinst! we don't have any specific plans for an dialyzer engine right now but if you (or anyone) would like to work on wrapping it up as an engine, we'd love to have it.  You can find our open source spec [here](https://github.com/codeclimate/spec).

We have a codeclimate-community slack organization where folks hang out to discuss engine ideas and development. If you're interested, you can join our [Developer Program](https://codeclimate.com/dev_form) to get an invite.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
