### ISSUE TITLE
Multiple formats

### ISSUE THREAD

**Issue by tomdavidson** [qltysh/codeclimate#790]
Can I have multiple formats such as HTML and JSON without running the engines more than once?

**Comment by CoenWarmer** [comment]
Would really be interested in this. Or perhaps a conversion script so we can transform a JSON report to an HTML report?

**Comment by tflori** [comment]
it would be helpful anyway. why to waste time running it twice when you just want different output formats of the same result? I suggest to have separate command line options for the analyze command: `codeclimate analyze --report-html code-climate.html --format json > code-climate.json` (this way we don't even have a breaking change)

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
