### ISSUE TITLE
Update eslint-plugin-ramda to latest version

### ISSUE THREAD

**Issue by Undistraction** [qltysh/codeclimate#819]
Please update your version of `eslint-plugin-ramda` to the latest release (v2.5.0) as it includes new rules.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
