### ISSUE TITLE
codeclimate cli may benefit from osx volume mount configurations

### ISSUE THREAD

**Issue by olbrich** [qltysh/codeclimate#830]
https://github.com/codeclimate/codeclimate/blob/18c2509474b0bdadad1174559257661a75131818/codeclimate-wrapper#L114

https://docs.docker.com/docker-for-mac/osxfs-caching/

it seems that adding `:cached` to the `/code`, config, and cached volumes and `:delegated` to the `/tmp/cc` volume may improve performance on OSX machines at least.

**Comment by wfleming** [comment]
This is a good suggestion, thanks, and sorry for the delay in reply here.

I think we'd be happy to see this a PR add this. My only concern is being sure this option has no negative effects on other platforms, e.g. Linux.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
