### ISSUE TITLE
Support for flowjs

### ISSUE THREAD

**Issue by Rafi993** [qltysh/codeclimate#863]
I have been trying to setup flowjs integration in code climate. I did search through the docs I couldn't find explicit information ( except for eslint flow plugin which does not run flow ). So is flowjs supported now if so how would I proceed with it now. If not will it be added in the future.

**Comment by wfleming** [comment]
@Rafi993 are there particular tools for linting Flow.js that you would like to see supported? I'm not familiar with Flow.js, but it seems like it's a pretty standard JS library, so normal JS code written using Flow should be analyzable by Code Climate's usual JavaScript analysis.

**Comment by Rafi993** [comment]
Yes support  for flowjs is a selling point for me. Flow comes with cli tool for linting. There are also some eslint plugins to run flow ( adding that support will also do )

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
