### ISSUE TITLE
Not properly detecting loc in the case of an es6 arrow function expression?

### ISSUE THREAD

**Issue by dfreire** [qltysh/codeclimate#895]
Hi,

We're running code climate on a React project and we have noticed something.

If we have a stateless component that exceeds the allowed number of lines of code, like:

```jsx
const SomeComponent = () => {
  return (
    <div>
      {/* ... dozens of lines of code ... */}
    </div>
  );
}
```

As expected, we get a code smell saying:
`Function SomeComponent has X lines of code (exceeds 50 allowed)`

But, if we change the code to the equivalent:
```jsx
const SomeComponent = () => (
  <div>
    {/* ... dozens of lines of code ... */}
  </div>
);
```
We don't get any code smell.

The same thing happens in regular es6 (non-React) code.

Why is that? Is it possible to fix this?

Thanks

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
