### ISSUE TITLE
SimpleCov Reporting Differences Between v0.17.1 and v0.18.0

### ISSUE THREAD

**Issue by ksylvest** [qltysh/codeclimate#937]
I'm running simplecov / codeclimate. Bumping from v0.17.1 to v0.18.0 of SimpleCov causes the reporter to fail:

```
#!/bin/bash -eo pipefail
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-$CC_TEST_REPORTER_VERSION > ./cc-test-reporter
chmod +x ./cc-test-reporter
./cc-test-reporter format-coverage -t simplecov coverage/.resultset.json
./cc-test-reporter upload-coverage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100   178  100   178    0     0  14833      0 --:--:-- --:--:-- --:--:-- 14833

100 12.1M  100 12.1M    0     0  82.8M      0 --:--:-- --:--:-- --:--:-- 82.8M
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-test-reporter format-coverage [coverage file] [flags]

Flags:
      --add-prefix string   add this prefix to file paths
  -t, --input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --prefix string       the root directory where the coverage analysis was performed (default "/home/circleci/project")

Global Flags:
  -d, --debug   run in debug mode


Exited with code exit status 255
```

Possibly related to the formatting?

Old: https://15129-99061924-gh.circle-artifacts.com/0/coverage/.resultset.json
New: https://15169-99061924-gh.circle-artifacts.com/0/coverage/.resultset.json

PR / CI for reference: https://github.com/ksylvest/playground/pull/892 / https://circleci.com/gh/ksylvest/playground/15169#artifacts/containers/0

**Comment by PragTob** [comment]
Hi there,

this is a known issue - you can find out more about the background etc. here: https://github.com/codeclimate/test-reporter/issues/413

Cheers,
Tobi

**Comment by ksylvest** [comment]
Thanks @PragTob

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
