### ISSUE TITLE
Exclude code patterns for duplication

### ISSUE THREAD

**Issue by sudansh** [qltysh/codeclimate#951]
If we could have a feature for excluded code patterns for duplication, it would be best.
For example in my Android project i have two classes with few common `imports`. And this comes as duplicate, which isn't a valid duplicated code.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
