### ISSUE TITLE
sonar-java version

### ISSUE THREAD

**Issue by zjuxxd** [qltysh/codeclimate#965]
Hi there!

I find sonar-java used in codeclimate is 4.14, which is released in 2017: https://docs.codeclimate.com/docs/sonar-java, now the latest version of sonar-java is 6.6, see https://github.com/SonarSource/sonar-java. Is there any reason why not upgrade to the latest version?

**Comment by artfuldodger** [comment]
Looks like we'd need https://github.com/codeclimate/sonar-java to be updated with the upstream before this repo could be updated?

**Comment by hudsonma** [comment]
Are there any updates on this?  sonar-java is now up to major version 7.  Any instructions or openness to a contribution on this repo and/or the codeclimate fork of sonar-java?

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
