### ISSUE TITLE
support for objective c

### ISSUE THREAD

**Issue by zjuxxd** [qltysh/codeclimate#966]
Hi there,

I see there is no Objective-C support right now: https://docs.codeclimate.com/docs/supported-languages-for-maintainability

Is there a plan to support it in the near future?

**Comment by efueger** [comment]
Hi @zjuxxd - 

Thanks for reaching out. 

And you're rigt: we don't offer any support (either through our maintainability checks or third-party plugins) for Objective C. I know that it's on our roadmap, but I don't have an ETA for that. 

(We do offer [maintainability](https://docs.codeclimate.com/docs/supported-languages-for-maintainability) and [Swiftlint](https://docs.codeclimate.com/docs/swiftlint) plugin support for Swift.)

Apologies for the wait! If you want to learn how create plugins for Objective C, you can check out this link: [Build your own Code Climate engine](http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/). To start that process you can:

- fill this out this [form](https://codeclimate.com/dev_form)
- and check out the specs [here](https://codeclimate.com/dev_form)


You'll then receive an invitation to join the Community Slack channel where you can chat with other engine developers. It's a great place to ask questions and find out about engines that folks are working on.

Let me know if you have any other questions or if there's anything else I can do to help.

**Comment by zjuxxd** [comment]
Hi efueger, thanks for you reply. I will find to use other solutions for Object C support.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
