### ISSUE TITLE
cppcheck docker update

### ISSUE THREAD

**Issue by luochongjun** [qltysh/codeclimate#989]
I notice that the cppcheck on docker.io is still a couple of years old, which is way too old.
https://hub.docker.com/r/codeclimate/codeclimate-cppcheck/tags

The latest cppcheck fixes a lot of bugs. Can you update that?
https://github.com/antiagainst/codeclimate-cppcheck/issues?q=is%3Aissue+is%3Aclosed

**Comment by kate-grechishkina** [comment]
Because the image is so old many cool features are unavailable when using it, like `inline-suppr`.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
